- name: roboshop project - mysql
  hosts: all
  become: true
  tasks:
    - name : mysql repo
      ansible.builtin.copy :
        src : mysql.repo
        dest : /etc/yum.repos.d/mysql.repo

    - name : disable msql
      ansible.builtin.shell : yum module disable mysql -y

    - name : install msql community server
      ansible.builtin.yum :
        - name : mysql
          state : installed

    - name : start mysql
      ansible.builtin.systemd :
        - name : mysql
          state : restarted
          enabled : yes

    - name : setting password
      ansible.builtin.shell : mysql_secure_installation --set-root-pass RoboShop@1
