- name: roboshop project - redis
  hosts: all
  become: true
  tasks:
    - name : download repo
      ansible.builtin.yum :
        src : https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
        state : installed

    - name : enable redis
      ansible.builtin.shell : yum module enable redis:remi-6.2 -y

    - name : install redis
      ansible.builtin.yum :
        name : redis
        state : installed

    - name : change ip address
      ansible.builtin.replace :
        src : /etc/redis.conf
        regexp : '127.0.0.1'
        replace : '0.0.0.0'

    - name: change ip address
      ansible.builtin.replace:
        src: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name : start redis
      ansible.builtin.systemd :
        name : redis
        state : restarted
        enabled : yes
