- name : user setup
  hosts : all
  become : true
  tasks :
    - name: service file
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: download nodejs
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

    - name: install nodejs
      ansible.builtin.yum:
        name: nodejs
        state: installed

    - name: add user
      ansible.builtin.user:
        name: roboshop

    - name: remove directory
      ansible.builtin.file:
        name: /app
        state: absent

    - name: create directory
      ansible.builtin.file:
        name: /app
        state: directory

    - name: download artifacts
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/user.zip
        dest: /app
        remote_src: yes

    - name: install dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app

    - name: copy repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: mongodb install
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: load schema
      ansible.builtin.shell: mongo --host mongodb-dev.sdevops28.online </app/schema/user.js

    - name: start user
      ansible.builtin.systemd:
        name: user
        state: restarted
        enabled: yes
        daemon-reload: yes